# cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY

# 声明使用 Secret
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/pgs-ins-bucket-name/versions/latest
      env: PGS_INS_BUCKET_NAME
    - versionName: projects/${PROJECT_ID}/secrets/pgs-ins-region/versions/latest
      env: PGS_INS_REGION
    - versionName: projects/${PROJECT_ID}/secrets/pgs-ins-project/versions/latest
      env: PGS_INS_PROJECT

steps:
  # 步骤 1: 设置 GCP 项目
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'config'
      - 'set'
      - 'project'
      - '${PGS_INS_PROJECT}'

  # 步骤 2: 检查或创建 GCS 存储桶
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if gsutil ls -b "gs://${PGS_INS_BUCKET_NAME}" >/dev/null 2>&1; then
          echo "Bucket already exists: gs://${PGS_INS_BUCKET_NAME}"
        else
          gsutil mb -p "${PGS_INS_PROJECT}" -l "${PGS_INS_REGION}" "gs://${PGS_INS_BUCKET_NAME}"
          echo "Created bucket: gs://${PGS_INS_BUCKET_NAME}"
        fi

  # 步骤 3: 初始化 Terraform
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args:
      - 'init'

  # 步骤 4: 执行 Terraform Plan
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args:
      - 'plan'
      - '-var-file=${_VAR_ENV_NAME}.tfvars'
      - '-out=plan.out'

  # 步骤 5: 执行 Terraform Apply
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args:
      - 'apply'
      - '-auto-approve'
      - 'plan.out'

  # 步骤 6: 完成部署
  - name: 'alpine'
    entrypoint: 'echo'
    args:
      - 'Deployment Complete for ${PGS_INS_PROJECT}'
