options:
  logging: CLOUD_LOGGING_ONLY

# 从 Secret Manager 获取机密信息
availableSecrets:
  secretManager:
    - versionName: projects/daytrader-dev-security/secrets/pgs-ins-bucket-name/versions/latest
      env: BUCKET_NAME
    - versionName: projects/daytrader-dev-security/secrets/pgs-ins-region/versions/latest
      env: REGION

steps:
  # 步骤 1: 设置 GCP 项目
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'config'
      - 'set'
      - 'project'
      - '$PROJECT_ID'

  # 步骤 2: 检查或创建 GCS 存储桶
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if gsutil ls -b "gs://$BUCKET_NAME" >/dev/null 2>&1; then
          echo "Bucket already exists: gs://$BUCKET_NAME"
        else
          gsutil mb -p "$PROJECT_ID" -l "$REGION" "gs://$BUCKET_NAME"
          echo "Created bucket: gs://$BUCKET_NAME"
        fi
    secretEnv:
      - BUCKET_NAME
      - REGION

  # 步骤 3: 初始化 Terraform
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args:
      - 'init'

  # 步骤 4: 执行 Terraform Plan
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args:
      - 'plan'
      - '-var-file=${_VAR_ENV_NAME}.tfvars'
      - '-out=plan.out'

  # 步骤 5: 执行 Terraform Apply
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args:
      - 'apply'
      - '-auto-approve'
      - 'plan.out'

  # 步骤 6: 完成部署
  - name: 'alpine'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Deployment Complete for $PROJECT_ID"'
