# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: 'bucket-daytrader-dev-data'

steps:
  # 步骤 1: 设置 GCP 项目
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'config'
      - 'set'
      - 'project'
      - 'daytrader-dev-data'

  # 步骤 2: 检查或创建 GCS 存储桶
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BUCKET_NAME="bucket-daytrader-dev-data"
        REGION="asia-northeast3"
        if gsutil ls -b "gs://$BUCKET_NAME" >/dev/null 2>&1; then
          echo "Bucket already exists: gs://$BUCKET_NAME"
        else
          gsutil mb -p "$PROJECT_ID" -l "$REGION" "gs://$BUCKET_NAME"
          echo "Created bucket: gs://$BUCKET_NAME"
        fi

  # 步骤 3: 初始化 Terraform
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args:
      - 'init'

  # 步骤 4: 执行 Terraform Plan，选择不同的变量文件
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args:
      - 'plan'
      - '-var-file=${_VAR_ENV_NAME}.tfvars'
      - '-out=plan.out'

  # 步骤 5: 执行 Terraform Apply
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args:
      - 'apply'
      - '-auto-approve'
      - 'plan.out'

  # 步骤 6: 完成部署
  - name: 'alpine'
    entrypoint: 'echo'
    args:
      - 'Deployment Complete'
